default: &default
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWD'] %>
  url: <%= ENV['FEDORA_URL'] %>

development:
  <<: *default
  base_path: /libra-oc/dev

test:
  <<: *default
  base_path: /libraoc/test

production:
  <<: *default
  base_path: /libra-oc/prod

