development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://docker1.lib.virginia.edu:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8055 %>/rest
  base_path: /libra-oc-dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://docker1.lib.virginia.edu:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8055 %>/rest
  base_path: /libra-oc
