default: &default
  admin:
    - dpg3k@virginia.edu
    - ecr2c@virginia.edu
    - lsc6v@virginia.edu
    - naw4t@virginia.edu
    - sah@virginia.edu

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

