# This is a sample config file that points to a solr server for each environment
development:
  url: <%= "http://docker1.lib.virginia.edu:#{ENV['SOLR_TEST_PORT'] || 8054}/solr/libra2" %>
test:
  url: http://docker1.lib.virginia.edu:<%= ENV['SOLR_TEST_PORT'] || 8054 %>/solr/libra2
production:
  url: <%= ENV['SOLR_URL'] %>/libra2
